version: '3'

services:
  web:
    build: .
    command: gunicorn django_practice_prj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/user/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_practice_db_user
      - POSTGRES_PASSWORD=django_practice_db_password
      - POSTGRES_DB=django_practice_dev

volumes:
  postgres_data: